name: Doctests

# TODO: Switch branch to rewrite-2023
on:
  push:
    branches: [ci-doctests]

concurrency:
  group: workflow-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doctests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Set up the environment
        run: python x.py setup
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared"
      - name: Run doctests
        run: uv run scripts/doctests/run_doctests.py ci
